test: &default

  # Credentials for REST APIs
  client_id: ASX4vffnFypZJg-j_dYn7LNFHFGHs79NO3aHOX04uzYUj36SOX3OJdZu3r7c8GHdEgwOf94FxKH4sFNU
  client_secret: ENMYhTqaWN5fi0UpOYR6RKs2Aa6eypwpnWwLDM3jeWwlQKu7pjknF4Y0yepl2voGVUQGouIg-DtYy3ya

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
